### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by naofum**

### CODE REVIEW

**Comment by szafir1100** [comment]
Great work!
Japanese translation surprised me very hard :smile: 
I'm going to make more translations today :)
Thanks for Your contribution!

PS. Some credits here for @mary-kate for making translations a lot easier

**Comment by szafir1100** [comment]
@naofum 
Could You translate this for google play store?
"Note has no text"
"Drawable Notepad is lightweight aplication that allows user to write some notes and draw on them."
"Drawable Notepad"
"Features:
Text format panel
Drawing panel
Search notes
Speech to text function
Saving notes in SQLite database"

Btw. "Drawable Notepad can be just notepad if You dont have any ideas of how You could translate that one :)

**Comment by naofum** [comment]
Hello Tomek,

Drawable Notepad is nice app!

And I translated for google play store.

"Note has no text"
"テキストのないメモ"

"Drawable Notepad is lightweight aplication that allows user to write some
notes and draw on them."
"描くメモ帳は、ユーザーがメモや絵を描くことができる軽量のアプリケーションです。"

"Drawable Notepad"
"描くメモ帳"

"Features:
Text format panel
Drawing panel
Search notes
Speech to text function
Saving notes in SQLite database"
"特徴:
テキスト形式のパネル
描画パネル
メモの検索
音声認識機能
SQLite データベースにメモを保存"

Regards,
Naofumi

2016-03-12 3:26 GMT+09:00 Tomek notifications@github.com:

**Comment by szafir1100** [comment]
Thanks for great support, im going to include this into google play store ASAP :)

PS. Im going to add localized graphics for google play store too :)

**Pull request merged**
